SECRET_KEY="your_secret_key_for_jsonwebtoken"
DB_NAME="your_postgre_db_name"
DB_PW="your_db_password"
DB_PORT="5432" # port of your db connection

# email 
NO_REPLY_EMAIL="your-no-reply-email@yourservicedomain.com" 
SMTP_USERNAME="your_smtp_username"
SMTP_PASSWORD="your_smtp_password"
SMTP_RELAY="your_smtp_password"
